### ISSUE TITLE
File Filtering

### ISSUE THREAD

**Issue by jekku** [winhowes/file-upload#10]
Is there any possible way to filter what files to upload?

**Comment by winhowes** [comment]
Will look at that this weekend, though if you want to do a PR for it, that would be warmly welcomed :)

**Comment by jekku** [comment]
@winhowes did one. :) I hope you can help me test it please.

**Comment by winhowes** [comment]
yep, I'll take look

**Comment by winhowes** [comment]
It's been added, and I've added a quick test for it!
