### ISSUE TITLE
Create mix-ins to style inner-elements

### ISSUE THREAD

**Issue by TimvdLippe** [winhowes/file-upload#13]
Mix-ins allow external users to style the inner-elements. An example: https://github.com/PolymerElements/paper-button/blob/master/paper-button.html#L101

**Comment by winhowes** [comment]
Cool, I'll add that in by Monday at the latest

**Comment by winhowes** [comment]
Cool, this should be closed with https://github.com/winhowes/file-upload/commit/e324d09d731858b584e748ad99be794ecd623f28
