### ISSUE TITLE
Prevent auto-upload?

### ISSUE THREAD

**Issue by danprime** [winhowes/file-upload#14]
Hi,

I noticed there's a method uploadFile() in the docs. Is there a way to turn off automatic uploading? i.e. I want to use this component as part of a wizard but I don't want to send it immediately to the server until I confirm with the user a few things.

**Comment by winhowes** [comment]
Hey! Let me see what I can add (probably won't get to this until next week). PRs are of course welcome!

**Comment by chisholmd** [comment]
Sorry to be daft but perhaps an example receiving page would be helpful.  Also, I don't see a name property.  I might be incorrect in assuming that I can have two or more upload tags each targeted to a different field in my database <file-upload name='selfie' />  <file-upload name='logo' />  which I would be able to refer to in my receiving script by name....no?  Also how to send other data eg. recordID?

Oh I think I see.  On a successful upload I can handle the success event and then make another call to update my database. I will check the examples some more.
