### ISSUE TITLE
tracking uploads

### ISSUE THREAD

**Issue by chisholmd** [winhowes/file-upload#18]
Thanks for the component it works well and looks nice.  I was having a hard time figuring out how to send other data along with the file being uploaded but it looks like using the "before-upload" event to add some custom headers might do the trick.

If there was a better way that you envisioned tracking uploads please let me know.

**Comment by winhowes** [comment]
Sorry for the delayed response! That would work, but I also just merged https://github.com/winhowes/file-upload/pull/19 which allows you to add additional params to the post request. Hope this helps!
