### ISSUE TITLE
Add notify: true to files

### ISSUE THREAD

**Issue by wq9** [winhowes/file-upload#22]
I needed more controls over how to display the list of files, so by adding `notify: true`, filename and progress bar can be displayed far away from the file input button element, like having the progress bar in a dialog box.

``` js
      files: {
        type: Array,
        notify: true,
        value: function() {
            return [];
        }
      },
```

If there any other method to change the display, let me know.

**Comment by winhowes** [comment]
Added it in. Thanks!
