### ISSUE TITLE
New option: paper-button-content

### ISSUE THREAD

**Issue by rumeshm** [winhowes/file-upload#32]
Can you add new option paper-button-content ?
https://github.com/winhowes/file-upload/pull/31

**Comment by winhowes** [comment]
This can be already be done. If you do something like this:

```
<file-upload>My custom text</file-upload>
```

You'll end up with custom text in the file-upload button. Feel free to re-open if this doesn't make sense or isn't working for you. In the meantime I'm going to close this and #31.
