### ISSUE TITLE
Will you update this to Polymer 2.0? (I hope so...)

### ISSUE THREAD

**Issue by mercmobily** [winhowes/file-upload#34]
This is the best maintained, most fantastic AJAX module for Polymer.
Are you going to update it so that it works with Polymer 2.0?

We are using it in our project, and are thinking of porting as soon as possible.

Once I know how to port things, I am happy to help too.

**Comment by winhowes** [comment]
Absolutely. I'll be looking into that this week hopefully, but PRs are welcome!

**Comment by mercmobily** [comment]
Hi,

Thanks for that.

Merc.

**Comment by winhowes** [comment]
Hey sorry for the delay in getting back to you. So 2.0 is currently not recommended for production. When that time comes around I'll be sure to upgrade. In the meantime I've upgraded support to the latest version of polymer and checked that things work as expected.
