### ISSUE TITLE
Destination file name

### ISSUE THREAD

**Issue by mlabarre** [winhowes/file-upload#38]
I love this module but how can I change destination file name ? Thanks

**Comment by ramveer93** [comment]
Hi I am not able to upload the file,It says error uploading file ,Can anyone please tell me how to set the target value, i am trying to run it in my local.
thanks

**Comment by winhowes** [comment]
@mlabarre sorry for the delayed response. The target to upload to can be set dynamically with the `target` attribute. Once the file is uploaded you can rename it to whatever you like.

Feel free to re-open if that doesn't solve your issue. I'll do my best to be more prompt on future responses.

@ramveer93 you must have a local server running that accepts files at the specified `target`.
