### ISSUE TITLE
Disabling multi-file

### ISSUE THREAD

**Issue by Inrego** [winhowes/file-upload#4]
Hey. It's currently not possible to disable multi-file. It's due to how boolean values are handled in Polymer (as boolean attribute values), where the only way to set it to false, is leave out the attribute. But that does not work since you've set the default value to 'true'. 

You can read more about the topic here: https://github.com/Polymer/polymer/issues/1812

Basicly, all boolean values should default to false.

Alternatively, you could change the attribute to a String type, and check for true/false values, if you do want the default value to be true.

**Comment by winhowes** [comment]
Great to know, will update!
