### ISSUE TITLE
Chrome bug referenced in code is fixed

### ISSUE THREAD

**Issue by dustinteel** [winhowes/file-upload#40]
The chrome bug referenced in the code is fixed and the workaround actually causes problems in IE  Because the bug is fixed, the workaround code should be removed.  See here https://bugs.chromium.org/p/chromium/issues/detail?id=234931 in the left panel where it says "Merged" and points to a different issue that is a duplicate of this one that is marked as "Fixed".

**Comment by dustinteel** [comment]
See PR at https://github.com/winhowes/file-upload/pull/41

**Comment by winhowes** [comment]
Great, I'll take a look. Thanks!

**Comment by dustinteel** [comment]
Issue fixed by #41 which has been merged.
